[build-system]
requires = [
    "setuptools", 
    "wheel",
    ]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "requests",
    "cdflib",
    "numpy",
    "pandas",
    "pyspedas",
]

[tool.black]
line-length = 120
target-version = ['py39', 'py310']
